In [145]:
import numpy as np
import sympy as sp
from scipy.linalg import eig

In [146]:
#Properties (N and mm)
E1 = 60800
E2 = 58250
v12 = 0.07
G12 = 4550
t = 0.21
v21 = v12 * E2 / E1

# Plate Parameters
a = 360
b = 360
m = 4
n = 4

# Loads
Nxx = -1
Nyy = 0
Nxy = 0

In [147]:
#Boundary conditions
u1tx = 1 ; u1rx = 1 ; u2tx = 0 ; u2rx = 1
v1tx = 0 ; v1rx = 1 ; v2tx = 0 ; v2rx = 1
w1tx = 0 ; w1rx = 1 ; w2tx = 0 ; w2rx = 1
u1ty = 0 ; u1ry = 1 ; u2ty = 0 ; u2ry = 1
v1ty = 0 ; v1ry = 1 ; v2ty = 0 ; v2ry = 1
w1ty = 0 ; w1ry = 1 ; w2ty = 0 ; w2ry = 1


#Boundary conditions
u1tx = 1 ; u1rx = 1 ; u2tx = 1 ; u2rx = 1
v1tx = 1 ; v1rx = 1 ; v2tx = 1 ; v2rx = 1
w1tx = 1 ; w1rx = 1 ; w2tx = 1 ; w2rx = 1
u1ty = 1 ; u1ry = 1 ; u2ty = 1 ; u2ry = 1
v1ty = 1 ; v1ry = 1 ; v2ty = 1 ; v2ry = 1
w1ty = 1 ; w1ry = 1 ; w2ty = 1 ; w2ry = 1


**[Q] in the principal direction**  pg. 52 chap 2 of the three regions

In [148]:
Q_0 = np.array([[E1/(1-v12*v21), v12*E2/(1-v12*v21), 0],
                 [v12*E2/(1-v12*v21), E2/(1-v12*v21),0],
                 [0, 0, G12]])

**[Q] rotated in theta direction** pg. 53 and 54 of chap 2

In [149]:
layup = [(45,'f'),(0,'f'),(0,'f'),(45,'f'),(0,'f'),(0,'f'),(45,'f')]
Q_layup = []

#Layup assembly
for theta in layup:
    c = np.cos(theta[0]*np.pi/180)
    s = np.sin(theta[0]*np.pi/180)

    T_real = np.array([[c**2, s**2, 2*c*s],
                       [s**2, c**2, -2*c*s],
                       [-c*s, c*s, c**2-s**2]])

    T_engineering =  np.array([[c**2, s**2, c*s],
                               [s**2, c**2, -c*s],
                               [-2*c*s, 2*c*s, c**2-s**2]])


    if theta[1] == 'f':
        Q_layup.append((np.linalg.inv(T_real))@Q_0@T_engineering)


**[A], [B], [D]** pg. 24 fo chap 4 of the three regions

In [150]:
t_position = [-3.5*t, -2.5*t, -1.5*t, -0.5*t, 0.5*t, 1.5*t, 2.5*t, 3.5*t]

A = np.zeros(9).reshape(3,3)
B = np.zeros(9).reshape(3,3)
D = np.zeros(9).reshape(3,3)

for i in enumerate(Q_layup):
    zk1 = t_position[i[0]+1]
    zk0 = t_position[i[0]]
    
    A += (zk1 - zk0)*i[1]
    B += (1/2)*(zk1**2 - zk0**2)*i[1]
    D += (1/3)*(zk1**3 - zk0**3)*i[1]


F = np.vstack([
    np.hstack([A, B]),
    np.hstack([B, D])
])

F = sp.Matrix(F)

### Rayleigh-Ritz formulation

In [151]:
Ny = sp.symbols('Ny')
xi, eta  = sp.symbols(['xi', 'eta'])

In [152]:
xi**4/8 - xi**2/4 + 0.125

xi**4/8 - xi**2/4 + 0.125

In [153]:
# Bardell terms
# Su
uf_xi = {0: u1tx*(0.25*xi**3 - 0.75*xi + 0.5),
        1: u1rx*(0.125*xi**3 - 0.125*xi**2 - 0.125*xi + 0.125),
        2: u2tx*(-0.25*xi**3 + 0.75*xi + 0.5),
        3: u2rx*(-1/8 - 1/8*xi + 1/8*xi**2 + 1/8*xi**3),
        4: xi**4/8 - xi**2/4 + 0.125,
        5: xi**5/8 - xi**3/4 + xi/8,
        6: 7*xi**6/48 - 5*xi**4/16 + 3*xi**2/16 - 0.0208333333333333,
        7: 3*xi**7/16 - 7*xi**5/16 + 5*xi**3/16 - xi/16,
        8: 33*xi**8/128 - 21*xi**6/32 + 35*xi**4/64 - 5*xi**2/32 + 0.0078125,
        9: 143*xi**9/384 - 33*xi**7/32 + 63*xi**5/64 - 35*xi**3/96 + 5*xi/128}

uf_eta = {0: u1ty*(0.25*eta**3 - 0.75*eta + 0.5),
        1: u1ry*(0.125*eta**3 - 0.125*eta**2 - 0.125*eta + 0.125),
        2: u2ty*(-0.25*eta**3 + 0.75*eta + 0.5),
        3: u2ry*(-1/8 - 1/8*xi + 1/8*xi**2 + 1/8*xi**3),
        4: eta**4/8 - eta**2/4 + 0.125,
        5: eta**5/8 - eta**3/4 + eta/8,
        6: 7*eta**6/48 - 5*eta**4/16 + 3*eta**2/16 - 0.0208333333333333,
        7: 3*eta**7/16 - 7*eta**5/16 + 5*eta**3/16 - eta/16,
        8: 33*eta**8/128 - 21*eta**6/32 + 35*eta**4/64 - 5*eta**2/32 + 0.0078125,
        9: 143*eta**9/384 - 33*eta**7/32 + 63*eta**5/64 - 35*eta**3/96 + 5*eta/128}

# Sv
vf_xi = {0: v1tx*(0.25*xi**3 - 0.75*xi + 0.5),
        1: v1rx*(0.125*xi**3 - 0.125*xi**2 - 0.125*xi + 0.125),
        2: v2tx*(-0.25*xi**3 + 0.75*xi + 0.5),
        3: v2rx*(-1/8 - 1/8*xi + 1/8*xi**2 + 1/8*xi**3),
        4: xi**4/8 - xi**2/4 + 0.125,
        5: xi**5/8 - xi**3/4 + xi/8,
        6: 7*xi**6/48 - 5*xi**4/16 + 3*xi**2/16 - 0.0208333333333333,
        7: 3*xi**7/16 - 7*xi**5/16 + 5*xi**3/16 - xi/16,
        8: 33*xi**8/128 - 21*xi**6/32 + 35*xi**4/64 - 5*xi**2/32 + 0.0078125,
        9: 143*xi**9/384 - 33*xi**7/32 + 63*xi**5/64 - 35*xi**3/96 + 5*xi/128}

vf_eta = {0: v1ty*(0.25*eta**3 - 0.75*eta + 0.5),
        1: v1ry*(0.125*eta**3 - 0.125*eta**2 - 0.125*eta + 0.125),
        2: v2ty*(-0.25*eta**3 + 0.75*eta + 0.5),
        3: v2ry*(-1/8 - 1/8*xi + 1/8*xi**2 + 1/8*xi**3),
        4: eta**4/8 - eta**2/4 + 0.125,
        5: eta**5/8 - eta**3/4 + eta/8,
        6: 7*eta**6/48 - 5*eta**4/16 + 3*eta**2/16 - 0.0208333333333333,
        7: 3*eta**7/16 - 7*eta**5/16 + 5*eta**3/16 - eta/16,
        8: 33*eta**8/128 - 21*eta**6/32 + 35*eta**4/64 - 5*eta**2/32 + 0.0078125,
        9: 143*eta**9/384 - 33*eta**7/32 + 63*eta**5/64 - 35*eta**3/96 + 5*eta/128}

#Sw
wf_xi = {0: w1tx*(0.25*xi**3 - 0.75*xi + 0.5),
        1: w1rx*(0.125*xi**3 - 0.125*xi**2 - 0.125*xi + 0.125),
        2: w2tx*(-0.25*xi**3 + 0.75*xi + 0.5),
        3: w2rx*(-1/8 - 1/8*xi + 1/8*xi**2 + 1/8*xi**3),
        4: xi**4/8 - xi**2/4 + 0.125,
        5: xi**5/8 - xi**3/4 + xi/8,
        6: 7*xi**6/48 - 5*xi**4/16 + 3*xi**2/16 - 0.0208333333333333,
        7: 3*xi**7/16 - 7*xi**5/16 + 5*xi**3/16 - xi/16,
        8: 33*xi**8/128 - 21*xi**6/32 + 35*xi**4/64 - 5*xi**2/32 + 0.0078125,
        9: 143*xi**9/384 - 33*xi**7/32 + 63*xi**5/64 - 35*xi**3/96 + 5*xi/128}

wf_eta = {0: w1ty*(0.25*eta**3 - 0.75*eta + 0.5),
        1: w1ry*(0.125*eta**3 - 0.125*eta**2 - 0.125*eta + 0.125),
        2: w2ty*(-0.25*eta**3 + 0.75*eta + 0.5),
        3: w2ry*(-1/8 - 1/8*xi + 1/8*xi**2 + 1/8*xi**3),
        4: eta**4/8 - eta**2/4 + 0.125,
        5: eta**5/8 - eta**3/4 + eta/8,
        6: 7*eta**6/48 - 5*eta**4/16 + 3*eta**2/16 - 0.0208333333333333,
        7: 3*eta**7/16 - 7*eta**5/16 + 5*eta**3/16 - eta/16,
        8: 33*eta**8/128 - 21*eta**6/32 + 35*eta**4/64 - 5*eta**2/32 + 0.0078125,
        9: 143*eta**9/384 - 33*eta**7/32 + 63*eta**5/64 - 35*eta**3/96 + 5*eta/128}

In [159]:
Su, Sv, Sw = [[]], [[]], [[]]

for i in range(m):
    for j in range(n):
        Su[0].append(uf_xi[i]*uf_eta[j])
        Sv[0].append(vf_xi[i]*vf_eta[j])
        Sw[0].append(wf_xi[i]*wf_eta[j])
Su, Sv, Sw = sp.Matrix(Su), sp.Matrix(Sv), sp.Matrix(Sw)


B0_11 = np.array((2/a) * sp.diff(Su, xi))
B0_22 = np.array((2/b) * sp.diff(Sv, eta))
B0_31 = np.array((2/b)*sp.diff(Su, eta))
B0_32 = np.array((2/a)*sp.diff(Sv, xi))
B0_43 = np.array(-(4/a**2) * sp.diff(Sw, xi, xi))
B0_53 = np.array(-(4/b**2) * sp.diff(Sw, eta, eta))
B0_63 = np.array(-2*(4/(a*b)) * sp.diff(Sw, xi, eta))
Z = np.zeros(m*n).reshape(1, m*n)

B0_kappa = sp.Matrix([
    np.hstack([*B0_11, *Z, *Z]),
    np.hstack([*Z, *B0_22, *Z]),
    np.hstack([*B0_31, *B0_32, *Z]),
    np.hstack([*Z, *Z, *B0_43]),
    np.hstack([*Z, *Z, *B0_53]),
    np.hstack([*Z, *Z, *B0_63])
])


F = sp.Matrix(F)


G = sp.Matrix([
    np.hstack([*Z, *Z, *sp.diff(Sw, xi)*(2/a)]),
    np.hstack([*Z, *Z, *sp.diff(Sw, eta)*(2/b)])
 ])


G = sp.Matrix([
    np.hstack([*sp.diff(Sw, xi)*(2/a)]),
    np.hstack([*sp.diff(Sw, eta)*(2/b)])
 ])

     

G = sp.Matrix(G)

N = sp.Matrix([[Nxx, Nxy],
                [Nxy, Nyy]])

In [160]:
G.shape

(2, 16)

In [161]:
KG = sp.integrate(
     sp.integrate(
        G.T * N * G, (xi, -1, 1)), (eta, -1, 1)
) * (a*b/4)

KG = np.array(KG, dtype=np.longdouble)

In [162]:
print(KG.shape)
print(KG.min())
print(KG.max())

(16, 16)
-0.44571428571428584
0.44571428571428584


In [123]:
K = sp.integrate(
    sp.integrate(
        B0_kappa.T * F * B0_kappa, (xi, -1, 1)), (eta, -1, 1)
) * (a*b/4)

K = np.array(K, dtype=np.longdouble)

KeyboardInterrupt: 

In [ ]:
print(K.shape)
print(K.min())
print(K.max())

(48, 48)
-235.90054625958584
1907.5827638713488


In [ ]:
A = K
B = KG

eig_values, eig_vectors = eig(A, B)

In [17]:
eig_values.min()

(nan+0j)

In [18]:
eig_values

array([nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j,
       nan+0.j, nan+0.j, inf+0.j, inf+0.j, inf+0.j, inf+0.j, inf+0.j,
       nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j,
       nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j,
       nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j,
       nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j,
       nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j, nan+0.j])

In [21]:
#eigvals, eigvecs = lb(A, B, silent=True)
#eigvals

## Check with compmech

In [102]:
from compmech.panel.panel import Panel
from compmech.analysis import lb, static

In [138]:
# skin panels
laminaprop = (E1, E2, v12, G12, G12, G12)
stack = [45, 0, 0, 45, 0, 0, 45,]
p1 = Panel(group='skin', Nxx=-1, x0=0, y0=0., a=a, b=b,m=4, n=4, plyt=t, stack=stack, laminaprop=laminaprop)

In [139]:
# boundary conditions CCCC
p1.u1tx = 1 ; p1.u1rx = 1 ; p1.u2tx = 0 ; p1.u2rx = 1
p1.v1tx = 0 ; p1.v1rx = 1 ; p1.v2tx = 0 ; p1.v2rx = 1
p1.w1tx = 0 ; p1.w1rx = 1 ; p1.w2tx = 0 ; p1.w2rx = 1
p1.u1ty = 0 ; p1.u1ry = 1 ; p1.u2ty = 0 ; p1.u2ry = 1
p1.v1ty = 0 ; p1.v1ry = 1 ; p1.v2ty = 0 ; p1.v2ry = 1
p1.w1ty = 0 ; p1.w1ry = 1 ; p1.w2ty = 0 ; p1.w2ry = 1


p1.u1tx = 1 ; p1.u1rx = 1 ; p1.u2tx = 1 ; p1.u2rx = 1
p1.v1tx = 1 ; p1.v1rx = 1 ; p1.v2tx = 1 ; p1.v2rx = 1
p1.w1tx = 1 ; p1.w1rx = 1 ; p1.w2tx = 1 ; p1.w2rx = 1
p1.u1ty = 1 ; p1.u1ry = 1 ; p1.u2ty = 1 ; p1.u2ry = 1
p1.v1ty = 1 ; p1.v1ry = 1 ; p1.v2ty = 1 ; p1.v2ry = 1
p1.w1ty = 1 ; p1.w1ry = 1 ; p1.w2ty = 1 ; p1.w2ry = 1


In [140]:
k0_1 = p1.calc_k0()
kG0_1 = p1.calc_kG0()

eigvals, eigvecs = lb(k0_1, kG0_1, silent=True)
eigvals

		Calculating k0... 
		finished!
		Calculating kG0... 
		finished!


array([ 8.27539521e-02,  1.54595188e-01,  4.08042946e-01,  5.94116455e-01,
        6.48313547e-01,  7.74355541e-01,  9.24892554e-01,  9.77911922e-01,
        1.76216653e+00,  1.96190749e+00,  1.97148250e+00,  2.00053501e+00,
        2.15920632e+00,  2.90021968e+00,  5.99112305e+00,  6.47529950e+00,
        6.83539355e+00,  9.46120800e+00,  3.47173313e+02, -6.01929297e+06,
       -6.32618179e+00, -1.77060881e-01, -1.65551654e-01, -1.00365130e-01,
       -1.33591893e-02])

In [141]:
print(k0_1.min())
print(k0_1.max())

-29823.298056988755
42847.26352960424


In [142]:
print(kG0_1.min())
print(kG0_1.max())

-0.4457142857142858
0.4457142857142858


In [143]:
sp.Matrix(kG0_1.toarray())

Matrix([
[0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                     0, 0, 0,                     0, 0, 0,                     0, 0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                     0, 0, 0,                     0, 0, 0,                     0],
[0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                     0, 0, 0,                     0, 0, 0,                     0, 0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                    0, 0, 0,                     0, 0, 0,                     0, 0, 0,                     0],
[0, 0,   -0.445714285714286, 0, 0,  -0.0371428571428572, 0, 0,    0.44571428571

In [163]:
sp.Matrix(KG)

Matrix([
[  -0.445714285714286,   -0.0628571428571429,  -0.154285714285714,  0.00714285714285718,  -0.0371428571428572,  -0.00523809523809524,  -0.0128571428571428,                     0,    0.445714285714286,   0.0628571428571429,    0.154285714285714,  -0.0571428571428572,  -0.0371428571428572,  -0.00523809523809524,  -0.0128571428571428,   0.00714285714285717],
[ -0.0628571428571429,   -0.0114285714285714, -0.0371428571428572,   0.0011904761904762, -0.00523809523809524, -0.000952380952380952,  -0.0030952380952381,                     0,   0.0628571428571429,   0.0114285714285714,   0.0371428571428572, -0.00952380952380953, -0.00523809523809524, -0.000952380952380952,  -0.0030952380952381,   0.00119047619047619],
[  -0.154285714285714,   -0.0371428571428572,  -0.445714285714286,  0.00714285714285718,  -0.0128571428571428,   -0.0030952380952381,  -0.0371428571428572,                     0,    0.154285714285714,   0.0371428571428572,    0.445714285714286,  -0.0571428571428572,  -0.0128

## Check with composipy

In [ ]:
from composipy import Laminate, Ply, buckling_load

In [ ]:
ply = Ply(E1, E2, v12, G12, t)
layup_1 = [(45, ply),(0, ply),(0, ply),(45, ply),(0, ply),(0, ply),(45, ply)]
laminate_1 = Laminate(layup_1)

In [ ]:
load = buckling_load(a, b, laminate_1.D, shape_plot = False , eig = True, n=10)

In [ ]:
a = abs(load['eigen values'])
a.sort()
a

array([4.14270828e+00, 6.21522205e+00, 1.06650914e+01, 1.65710358e+01,
       1.70242153e+01, 1.91554561e+01, 2.45809295e+01, 2.48385030e+01,
       2.52623245e+01, 3.27636136e+01, 3.53001050e+01, 3.72839695e+01,
       4.01613869e+01, 4.26490962e+01, 4.27935413e+01, 4.67661371e+01,
       4.71871495e+01, 5.44108590e+01, 5.59663308e+01, 6.09072064e+01,
       6.62675469e+01, 6.72164889e+01, 6.81862074e+01, 6.93560842e+01,
       7.10330003e+01, 7.64561102e+01, 7.66218673e+01, 8.06194972e+01,
       8.36422449e+01, 8.68293907e+01, 9.38431588e+01, 9.44488356e+01,
       9.59106601e+01, 9.83663621e+01, 9.94734984e+01, 1.00992872e+02,
       1.03585297e+02, 1.06783130e+02, 1.07936385e+02, 1.13012131e+02,
       1.14423916e+02, 1.14554965e+02, 1.25606923e+02, 1.28759733e+02,
       1.31058289e+02, 1.39329386e+02, 1.49151952e+02, 1.52444711e+02,
       1.53256367e+02, 1.55402551e+02, 1.60648911e+02, 1.71172156e+02,
       1.72395090e+02, 1.87014978e+02, 2.01935205e+02, 2.03008923e+02,
      